type = "javascript"
name = "search"
account_id = "44321e1b7fbd29b56b65c1890a3bbee2"


[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"
dir = "build"

[miniflare]
kv_persist = true